Repository andela/blackninjas-backend, pull requests merged in 2020-01, with the labels that each got.

#22 ft(create trip): create return trip
  package-lock.json
  package.json
  src/app.js
  src/controllers/trips.controller.js
  src/controllers/user.controller.js
  src/database/migrations/20191209132840-create-user.js
  src/database/migrations/20191224124342-create-locations.js
  src/database/migrations/20191230103013-create-user.js
  src/database/migrations/20200102173505-create-accomodationtype.js
  src/database/migrations/20200102215044-create-accomodation.js
  src/database/migrations/20200103052813-create-usermanagement.js
  src/database/migrations/20200104124748-create-rooms.js
  src/database/migrations/20200104125058-create-trips.js
  src/database/migrations/20200104125319-create-requesttrip.js
  src/database/models/accomodation.js
  src/database/models/accomodationtype.js
  src/database/models/locations.js
  src/database/models/requesttrip.js
  src/database/models/rooms.js
  src/database/models/trips.js
  src/database/models/user.js
  src/database/models/usermanagement.js
  src/database/seeders/20191209093509-user.js
  src/database/seeders/20191224144425-locations.js
  src/helpers/response.helper.js
  src/helpers/token.helper.js
  src/helpers/verify.token.helper.js
  src/middlewares/check.trip.middleware.js
  src/middlewares/user.middleware.js
  src/middlewares/verify.token.middleware.js
  src/middlewares/verify.user.middleware.js
  src/routes/index.js
  src/routes/trips.route.js
  src/routes/user.route.js
  src/services/Queries.js
  src/services/trips.services.js
  src/services/user.service.js
  src/swagger/index.js
  src/tests/0000ztrips.js
  src/tests/user/tripsData.js
  src/tests/user/userData.js
Labels: ready

#23 #169817871 user create one way trip
  .DS_Store
  src/controllers/trips.controller.js
  src/controllers/user.controller.js
  src/database/migrations/20191209132840-create-user.js
  src/database/migrations/20191224124342-create-locations.js
  src/database/migrations/20200103053121-create-rooms.js
  src/database/models/accomodationType.js
  src/database/models/locations.js
  src/database/models/requesttrip.js
  src/database/models/trips.js
  src/database/models/user.js
  src/helpers/token.helper.js
  src/helpers/validate.helper.js
  src/middlewares/check.trip.middleware.js
  src/middlewares/user.middleware.js
  src/routes/trips.route.js
  src/services/Queries.js
  src/services/trips.services.js
  src/tests/0000ztrips.js
  src/tests/user/tripsData.js
Labels: completed, ready

#31 #170549117 (fix-one way trip)refactor middlewares and controllers
  src/controllers/trip.controller.js
  src/controllers/trips.controller.js
  src/middlewares/accomodation.middleware.js
  src/middlewares/check.trip.middleware.js
  src/middlewares/trip.middleware.js
  src/routes/trips.route.js
  src/services/Queries.js
  src/services/accomodation.service.js
  src/services/trip.services.js
  src/services/user.service.js
  src/tests/0000ztrips.js
Labels: completed, ready

#27 feat(multicities): multi cities request
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/controllers/trip.controller.js
  src/database/migrations/20200102173505-create-accomodationtype.js
  src/database/migrations/20200102215044-create-accomodation.js
  src/database/migrations/20200103052813-create-usermanagement.js
  src/database/migrations/20200103053121-create-rooms.js
  src/database/migrations/20200103054547-create-trips.js
  src/database/migrations/20200104125319-create-requesttrip.js
  src/database/models/requesttrip.js
  src/database/models/rooms.js
  src/database/models/trips.js
  src/database/seeders/20191224144425-locations.js
  src/helpers/accomodation.helper.js
  src/helpers/joi.validate.js
  src/helpers/trip.helper.js
  src/middlewares/accomodation.middleware.js
  src/middlewares/trip.middleware.js
  src/middlewares/validate.middleware.js
  src/routes/index.js
  src/routes/trip.route.js
  src/services/Queries.js
  src/services/accomodation.services.js
  src/services/location.services.js
  src/services/room.services.js
  src/services/trip.services.js
  src/services/user.management.services.js
  src/swagger/index.js
  src/tests/0000ztrips.js
  src/tests/mock/trip.mock.data.js
  src/tests/multi.city.test.js
Labels: completed, ready

#26 #169817868 User can logout
  package.json
  src/controllers/trip.controller.js
  src/controllers/user.controller.js
  src/database/migrations/20191209132840-create-user.js
  src/database/models/user.js
  src/helpers/accomodation.helper.js
  src/helpers/profile.helper.js
  src/helpers/token.helper.js
  src/helpers/trip.helper.js
  src/helpers/verify.token.helper.js
  src/middlewares/user.middleware.js
  src/routes/user.route.js
  src/services/user.service.js
  src/tests/0000ztrips.js
  src/tests/000users.js
  src/tests/login.test.js
  src/tests/mock/trip.mock.data.js
  src/tests/multi.city.test.js
  src/tests/reset.password.test.js
  src/tests/social_auth.tests.js
  src/tests/user/tripsData.js
  src/tests/user/userData.js
  src/tests/userProfile.test.js
Labels: ready

#33 #169817879 avail request for approval
  src/controllers/trip.controller.js
  src/database/migrations/20200104125058-create-trips.js
  src/database/models/accomodationtype.js
  src/helpers/paginate.helper.js
  src/helpers/trip.helper.js
  src/middlewares/auth.middleware.js
  src/middlewares/user.middleware.js
  src/middlewares/verify.manager.middleware.js
  src/routes/trip.route.js
  src/services/Queries.js
  src/services/trip.services.js
  src/tests/0000ztrips.js
Labels: completed, ready

#28 #169817876 User requests Table
  .eslintignore
  barefootnomad.log
  src/controllers/trip.controller.js
  src/database/migrations/20191209132840-create-user.js
  src/database/migrations/20200104125319-create-requesttrip.js
  src/routes/trip.route.js
  src/routes/user.route.js
  src/services/Queries.js
  src/services/trip.services.js
  src/tests/getUserRequests.test.js
Labels: completed, ready

#35 #170570895 #169817878 Manager should be able to approve or reject a trip request
  Procfile
  package.json
  src/controllers/trip.controller.js
  src/controllers/user.controller.js
  src/middlewares/request.middleware.js
  src/routes/trip.route.js
  src/services/Queries.js
  src/services/request.services.js
  src/services/user.service.js
  src/swagger/index.js
  src/tests/0000ztrips.js
  src/tests/social_auth.tests.js
  src/tests/user/tripsData.js
Labels: ready

#30 #169817877 User Role Settings
  package.json
  src/controllers/user.controller.js
  src/database/migrations/20200107075515-create-user-role.js
  src/database/models/user.js
  src/database/models/userrole.js
  src/database/seeders/20200107083448-userRole.js
  src/middlewares/admin.verify.middleware.js
  src/routes/index.js
  src/routes/user.route.js
  src/routes/user.settings.route.js
  src/services/user.service.js
  src/swagger/index.js
  src/tests/userRole.test.js
Labels: completed, ready

#29 #169817874 new travel request notification
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/app.js
  src/controllers/notification.controller.js
  src/controllers/trip.controller.js
  src/database/migrations/20191209132840-create-user.js
  src/database/migrations/20191230124704-create-notification.js
  src/database/models/notification.js
  src/database/models/user.js
  src/helpers/socket.helper.js
  src/helpers/validate.helper.js
  src/index.js
  src/routes/index.js
  src/routes/notification.route.js
  src/services/notification.service.js
  src/services/user.service.js
  src/tests/znotification.test.js
Labels: completed, ready

#38 #170645837 fix features errors that are not working on heroku
  src/config/passport.config.js
  src/controllers/user.controller.js
  src/helpers/send.email.helper.js
  src/middlewares/verify.manager.middleware.js
  src/routes/user.route.js
  src/tests/000users.js
  src/tests/00signup.test.js
Labels: ready

#40 #169817831 Marking all notifications as read
  src/controllers/notification.controller.js
  src/helpers/validate.helper.js
  src/public/index.html
  src/routes/notification.route.js
  src/services/notification.service.js
  src/tests/znotification.test.js
Labels: completed, ready

#39 #169817883 delete trip request comment
  src/controllers/trip.controller.js
  src/controllers/user.controller.js
  src/database/migrations/20200108182413-create-comment.js
  src/database/models/comment.js
  src/database/models/trips.js
  src/helpers/accomodation.helper.js
  src/helpers/id.validator.helper.js
  src/helpers/trip.helper.js
  src/helpers/validate.helper.js
  src/middlewares/accomodation.middleware.js
  src/middlewares/comment.validation.middleware.js
  src/middlewares/trip.middleware.js
  src/routes/comment.routes.js
  src/routes/index.js
  src/services/Queries.js
  src/services/accomodation.service.js
  src/services/accomodation.services.js
  src/services/comment.service.js
  src/services/location.services.js
  src/services/room.services.js
  src/services/trip.services.js
  src/swagger/index.js
  src/tests/00signup.test.js
  src/tests/comment.test.js
  src/tests/mock/comment.mock.data.js
  src/tests/mock/trip.mock.data.js
  src/tests/multi.city.test.js
  src/tests/user/userData.js
  src/tests/znotification.test.js
Labels: ready

#36 #169817880 get a specific trip request
  src/controllers/trip.controller.js
  src/routes/index.js
  src/routes/trip-requests.route.js
  src/routes/trip.route.js
  src/services/trip.services.js
  src/tests/comment.test.js
Labels: completed

#44 #170752560 fix bug in trip request and add limit, descending order in get comment endpoint
  src/controllers/trip.controller.js
  src/public/index.html
  src/services/Queries.js
  src/services/trip.services.js
  src/tests/comment.test.js
Labels: completed, ready

#46 #169817884: Implement search functionality
  src/controllers/trip.controller.js
  src/public/index.html
  src/routes/index.js
  src/routes/search.route.js
  src/routes/trip-requests.route.js
  src/routes/trip.route.js
  src/services/request.services.js
  src/services/trip.services.js
  src/swagger/index.js
  src/tests/0000ztrips.js
Labels: ready for review

#37 #169817890 Travel Admin Create Accommodation facility
  package.json
  src/controllers/accomodation.controller.js
  src/database/migrations/20200102215044-create-accomodation.js
  src/database/migrations/20200102215045-create-accomodation-numberofrooms.js
  src/database/migrations/20200103053121-create-rooms.js
  src/database/migrations/20200110011038-create-image.js
  src/database/migrations/20200114165124-create-accomodationservice.js
  src/database/migrations/20200114165347-create-accomodationamenity.js
  src/database/models/accomodation.js
  src/database/models/accomodationamenity.js
  src/database/models/accomodationservice.js
  src/database/models/image.js
  src/database/models/rooms.js
  src/helpers/accomodation.helper.js
  src/helpers/validate.helper.js
  src/middlewares/accomodation.middleware.js
  src/routes/accommodation.route.js
  src/routes/index.js
  src/services/Queries.js
  src/services/accomodation.service.js
  src/services/image.services.js
  src/services/room.services.js
  src/tests/userRole.test.js
  src/tests/zzcreate.accomodation.test.js
Labels: ready for review

#41 #169817895 Pre Screened Supplier can create Accommodation
  src/middlewares/accomodation.middleware.js
  src/services/accomodation.service.js
Labels: completed, ready for review

#42 #169817886:user edit trip request
  src/controllers/trip.controller.js
  src/controllers/user.controller.js
  src/helpers/joi.validate.js
  src/helpers/verify.token.helper.js
  src/middlewares/accomodation.middleware.js
  src/middlewares/auth.middleware.js
  src/middlewares/trip.middleware.js
  src/middlewares/verify.token.middleware.js
  src/routes/index.js
  src/routes/trip-requests.route.js
  src/routes/trip.route.js
  src/services/Queries.js
  src/services/accomodation.service.js
  src/services/request.services.js
  src/services/trip.services.js
  src/tests/0000ztrips.js
  src/tests/getUserRequests.test.js
  src/tests/multi.city.test.js
  src/tests/user/tripsData.js
  src/tests/znotification.test.js
Labels: completed, ready for review

#45 #169817894:A manager should get notification of edited trip requests from their direct reports
  src/controllers/trip.controller.js
  src/controllers/user.controller.js
  src/public/index.html
  src/routes/trip-requests.route.js
  src/services/request.services.js
  src/tests/comment.test.js
Labels: completed, ready for review

#49 #169817896 Book an accommodation facility
  src/controllers/accomodation.controller.js
  src/database/migrations/20200121072843-create-booking.js
  src/database/models/booking.js
  src/helpers/validate.helper.js
  src/middlewares/accomodation.middleware.js
  src/routes/accommodation.route.js
  src/routes/index.js
  src/services/accomodation.service.js
  src/services/room.services.js
  src/tests/0000ztrips.js
  src/tests/zzzaccommodation.test.js
Labels: completed, ready for review

#52 #169817901 The most travelled destinations
  .eslintrc.json
  src/controllers/lacations.controller.js
  src/routes/accommodation.route.js
  src/routes/index.js
  src/routes/locations.route.js
  src/services/location.services.js
  src/swagger/index.js
  src/tests/zlocations.test.js
Labels: completed, ready for review

#50 #169817900 User should be able to get statistics of trips made in the last X timeframe
  src/controllers/trip.controller.js
  src/routes/index.js
  src/routes/trip.route.js
  src/routes/trip.statistics.route.js
  src/services/Queries.js
  src/services/trip.services.js
  src/swagger/index.js
  src/tests/0000ztrips.js
Labels: ready for review

#47 #169817898 add, get and delete a feedback of accommodation facility
  src/controllers/accomodation.controller.js
  src/controllers/trip.controller.js
  src/helpers/trip.helper.js
  src/middlewares/comment.validation.middleware.js
  src/routes/accommodation.route.js
  src/routes/comment.routes.js
  src/routes/index.js
  src/routes/trip-requests.route.js
  src/services/comment.service.js
  src/swagger/index.js
  src/tests/comment.test.js
  src/tests/mock/comment.mock.data.js
Labels: completed, ready for review

#51 #169817889 receive notifications for posted comments
  src/controllers/trip.controller.js
  src/public/index.html
  src/services/comment.service.js
  src/tests/comment.test.js
Labels: completed, ready for review

#48 #169817897 Like and unlike an accommodation facility
  package.json
  src/controllers/accomodation.controller.js
  src/database/migrations/20200108182413-create-likes-unlikes-accommodation.js
  src/database/migrations/20200120132215-create-accommodationLikesAndUnlikes.js
  src/database/models/accommodationLikesAndUnlikes.js
  src/database/models/accomodation.js
  src/helpers/validate.helper.js
  src/routes/accommodation.route.js
  src/services/accomodation.service.js
  src/tests/zzzaccommodation.test.js
Labels: completed, ready for review

#55 #170920146 refactor accommodation middleware
  src/middlewares/accomodation.middleware.js
  src/middlewares/comment.validation.middleware.js
  src/routes/accommodation.route.js
  src/services/Queries.js
  src/services/accomodation.service.js
  src/tests/comment.test.js
Labels: completed, ready for review

#54 feat(chat): users should be able to chat on barefoot nomad
  src/controllers/chat.controller.js
  src/database/migrations/20200123094705-create-chats.js
  src/database/models/chats.js
  src/helpers/socket.helper.js
  src/public/index.html
  src/routes/chat.route.js
  src/routes/index.js
  src/routes/user.route.js
  src/routes/user.settings.route.js
  src/services/Queries.js
  src/services/chat.service.js
  src/services/user.service.js
  src/tests/chat.test.js
Labels: ready for review

#53 #169817899:user rate and get average rate of an accommodation
  src/controllers/accomodation.controller.js
  src/database/migrations/20200102215046-create-accomodation-rate.js
  src/database/migrations/20200121073529-create-accomodation-rates.js
  src/database/models/accomodation.js
  src/database/models/accomodationrates.js
  src/database/models/booking.js
  src/helpers/accomodation.helper.js
  src/middlewares/accomodation.middleware.js
  src/routes/accommodation.route.js
  src/services/Queries.js
  src/services/accomodation.service.js
  src/services/trip.services.js
  src/tests/zzzzaccommodation.test.js
Labels: completed, ready for review
