Repository andela/blackninjas-backend, pull requests merged in 2020-02, with the labels that each got.

#57 ch(reset link):change redirect link
  src/helpers/send.email.helper.js
Labels: completed, ready for review

#58 #171122206 get app and email notification setting
  src/helpers/profile.helper.js
Labels: completed, ready for review

#63 #171324322 changing get users response data
  src/services/user.service.js
Labels: completed, ready for review

#61 #171240760 Admin should be able to assign users to their managers
  src/controllers/trip.controller.js
  src/controllers/user.controller.js
  src/database/seeders/20191209093509-user.js
  src/helpers/verify.token.helper.js
  src/middlewares/user-manager.middleware.js
  src/routes/index.js
  src/routes/user-management.route.js
  src/services/user-management.services.js
  src/services/user.management.services.js
  src/swagger/index.js
  src/tests/0000ztrips.js
  src/tests/userRole.test.js
Labels: ready for review

#64 ch(one way trip): fixing one way trip request
  barefootnomad.log
  src/controllers/accomodation.controller.js
  src/controllers/lacations.controller.js
  src/routes/accommodation.route.js
  src/routes/locations.route.js
  src/services/location.services.js
  src/tests/zlocations.test.js
  src/tests/zzcreate.accomodation.test.js
Labels: ready for review

#70 chore(one way trip): fixing response of getting supported locations
  src/controllers/lacations.controller.js
Labels: ready for review

#74 bug(add user id): user ID should be appeared in user profile information
  src/helpers/profile.helper.js
Labels: completed, ready for review

#72 #171464983 add user info on each comment retrieved.
  src/database/models/comment.js
  src/database/models/user.js
  src/services/Queries.js
  src/services/comment.service.js
  src/tests/chat.test.js
  src/tests/comment.test.js
Labels: completed

#75 Add last name of the manager in the user and their managers endpoint
  src/services/user-management.services.js
Labels: ready for review
